#!/usr/bin/env php
<?php
// doctrine
require_once "vendor/autoload.php";
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;

// Adjust this path to your actual bootstrap.php
require __DIR__ . '/bor/bootstrap.php';

ConsoleRunner::run(
    new SingleManagerProvider($entityManager)
);